apiVersion: v1
kind: Service

metadata:
  name: platform-demo
  namespace: platform-demo

spec:
  selector:
    app: platform-demo

  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

  type: ClusterIP